main.pdf:
	pdflatex "-shell-escape main.tex"

bibtex "main"

pdflatex "-shell-escape main.tex"

pdflatex "-shell-escape main.tex"

pdflatex "Introduction"

bibtex "Introduction"

pdflatex "Introduction"

pdflatex "Introduction"
